#!/bin/bash -e
#
# Convert to mp3 all *.flac files within a directory using high quality VBR
# Storage space is cheap nowadays. So a VBR with maximum quality was chosen.
# See also:
# https://wiki.archlinux.org/index.php/Convert_Flac_to_Mp3
# https://trac.ffmpeg.org/wiki/Encode/MP3
#

# Do not destroy directories. Exit on error
set -e

for a in ./*.flac; do
	ffmpeg -i "$a" -qscale:a 0 "${a[@]/%flac/mp3}"
done

#rm *.flac
